// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BdI9ioJYahZIb1cEsTLfIKAlcjVobB8',
    appId: '1:298268560760:web:aaaa14c3ff481501b90c8d',
    messagingSenderId: '298268560760',
    projectId: 'rent-all-things-in-one-place',
    authDomain: 'rent-all-things-in-one-place.firebaseapp.com',
    storageBucket: 'rent-all-things-in-one-place.appspot.com',
    measurementId: 'G-3472LB8XD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkL1OXjvoNOvPklmQBrswTOFYKUDxNxQI',
    appId: '1:298268560760:android:76814018b4d7d8beb90c8d',
    messagingSenderId: '298268560760',
    projectId: 'rent-all-things-in-one-place',
    storageBucket: 'rent-all-things-in-one-place.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyWOAMSS4ipI7VFEAsjgJx3EYNxKxqks',
    appId: '1:298268560760:ios:b5db16e29202f7c1b90c8d',
    messagingSenderId: '298268560760',
    projectId: 'rent-all-things-in-one-place',
    storageBucket: 'rent-all-things-in-one-place.appspot.com',
    androidClientId: '298268560760-uervoao36rgkee22gr22vgj9i8s0rmdj.apps.googleusercontent.com',
    iosClientId: '298268560760-71qfhlsav1ehqv3t65b1jcacev656b7p.apps.googleusercontent.com',
    iosBundleId: 'com.sinasys.gorest.cleanArchitectureGetx',
  );

}